### ISSUE TITLE
[NPM scripts] Status of npm build and test scripts

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/vigour-native#114]
## My setup:
My current setup to check if something is wrong there:

* **vigour-native** cloned clean from develop branch
* **gaston** installed globally from npm

## Scripts results:
Console output from scripts:

#### installtestapp
Installs npm dependencies for `test/app`. I don't see any errors and it looks like dependencies are installed in `test/app`node_modules` folder

#### buildtestapp
Runs `npm build` inside `test/app`. No strange output. @shawninder what should be the expected output? How can I check it?

#### test-bridge
The script tries to execute tests in `test/phantom/bridge` but the folder doesn't exists. @shawninder is the script necessary or we can remove it?

#### test-builder
The script builds the test app and then  runs tests against the builder script. Seems tests are working fine.

#### test-ios
Works fine. The result is an xcode project and if I launch the app I see just a big green screen. @shawninder is that correct?

#### test-android
I made some progress with Android build but it looks like it can't find a package needed for building the app, take a look at the log:

```bash
 ~/w/vigour-native   develop *  npm run test-android

> vigour-wrapper@1.0.2 test-android /Users/ninjatux/workspace/vigour-native
> npm run buildtestapp && gaston test -r node -s test/node/android/


> vigour-wrapper@1.0.2 buildtestapp /Users/ninjatux/workspace/vigour-native
> ./buildtestapp.js


> test-app@0.0.1 build /Users/ninjatux/workspace/vigour-native/test/app
> gaston build -s src -o . -i

info gaston build completed successfully
info gaston tester running node tests from /Users/ninjatux/workspace/vigour-native/test/node/android/


  android-scripts
    installTemplate
      ✓ should copy all files to empty dir
      ✓ should not copy build and Android Studio files
      ✓ should not copy older files (109ms)
      ✓ should overwrite newer files (1124ms)
      ✓ should overwrite main java and gradle file (146ms)
    customizeTemplate
info - customize template -
      ✓ should set path of js app
      ✓ should set app name
      ✓ should set splash timeout
    installImages
      ✓ should do nothing without options (336ms)
      1) should create launch icons from image
      2) should create splash screens from image
      ✓ should skip images that are already resized
    installing plugins
      - should init all plugins in main java file
      - should add all plugin libs as dependency
      - should add all plugin permissions to the manifest
info - installing plugins -
info plugins undefined
      ✓ should work without any plugins
    assemble
info - start assemble -
      ✓ should call gradle with params for the relevant options
    install & run
      ✓ should not install & run if not set in options
      ✓ should install & run if set in options
      ✓ should use correct options to install apk
      ✓ should use correct options to run app

  android build
info ---- Building Android ----
info - copying android template -
info   from /Users/ninjatux/workspace/vigour-native/templates/android/app
info   to /Users/ninjatux/workspace/vigour-native/test/app/build/android
info    force: /app/build.gradle
info    force: /app/src/main/java/io/vigour/nativewrapper/MainActivity.java
info start waiting
info done waiting
info - copy done -
info - copying assets -
info assets { 'build.html': true, 'build.js': true, 'build.css': true }
info root /Users/ninjatux/workspace/vigour-native/test/app
info val { 'build.html': true, 'build.js': true, 'build.css': true }
info resources { 'build.html': true, 'build.js': true, 'build.css': true }
info copying /Users/ninjatux/workspace/vigour-native/test/app/build.html to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/src/main/assets/build.html
info copying /Users/ninjatux/workspace/vigour-native/test/app/build.js to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/src/main/assets/build.js
info copying /Users/ninjatux/workspace/vigour-native/test/app/build.css to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/src/main/assets/build.css
info - customize template -
info - installing images -
info skippin up to date image assets/img/appIcon.png
info skippin up to date image assets/img/splash.png
info - installing plugins -
info plugins [ { android:
info plugins      { className: 'io.vigour.plugin',
info plugins        instantiation: 'new Plugin(this, webview)',
info plugins        skipInstall: true },
info plugins     name: 'vigour-plugin' } ]
info   installing plugin:  { android:
info   installing plugin:     { className: 'io.vigour.plugin',
info   installing plugin:       instantiation: 'new Plugin(this, webview)',
info   installing plugin:       skipInstall: true },
info   installing plugin:    name: 'vigour-plugin' }
info [object Object]
info   installIntoTemplate
info   inject into java
info save to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/src/main/java/io/vigour/nativewrapper/MainActivity.java
info   inject into AndroidManifest
info   inject into build.gradle
info save to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/build.gradle
info - start assemble -
info copy keystore file from: /Users/ninjatux/workspace/vigour-native/test/app/example.keystore to /Users/ninjatux/workspace/vigour-native/test/app/build/android/app/release.keystore
info Executing ./gradlew assembleRelease -PverCode=27 -PverName=2.1.4 -PandroidAppId=org.test -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********
info in /Users/ninjatux/workspace/vigour-native/test/app/build/android
Download https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/11.40.277.7/xwalk_core_library-11.40.277.7.pom
Download https://jcenter.bintray.com/com/fasterxml/jackson/jr/jackson-jr-objects/2.5.1/jackson-jr-objects-2.5.1.pom
Download https://jcenter.bintray.com/com/fasterxml/jackson/jr/jackson-jr-parent/2.5.1/jackson-jr-parent-2.5.1.pom
Download https://jcenter.bintray.com/com/fasterxml/jackson/jackson-parent/2.5/jackson-parent-2.5.pom
Download https://jcenter.bintray.com/com/fasterxml/oss-parent/18/oss-parent-18.pom
Download https://jcenter.bintray.com/com/facebook/android/facebook-android-sdk/4.0.0/facebook-android-sdk-4.0.0.pom
Download https://jcenter.bintray.com/joda-time/joda-time/2.7/joda-time-2.7.pom
Download https://jcenter.bintray.com/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.pom
Download https://jcenter.bintray.com/com/parse/bolts/bolts-android/1.1.4/bolts-android-1.1.4.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find any version that matches io.vigour.plugin:core:+.
     Searched in the following locations:
         https://jcenter.bintray.com/io/vigour/plugin/core/maven-metadata.xml
         https://jcenter.bintray.com/io/vigour/plugin/core/
         file:/Users/ninjatux/.m2/repository/io/vigour/plugin/core/maven-metadata.xml
         file:/Users/ninjatux/.m2/repository/io/vigour/plugin/core/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/io/vigour/plugin/core/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/io/vigour/plugin/core/
         file:/Users/ninjatux/Library/Android/sdk/extras/android/m2repository/io/vigour/plugin/core/maven-metadata.xml
         file:/Users/ninjatux/Library/Android/sdk/extras/android/m2repository/io/vigour/plugin/core/
         file:/Users/ninjatux/Library/Android/sdk/extras/google/m2repository/io/vigour/plugin/core/maven-metadata.xml
         file:/Users/ninjatux/Library/Android/sdk/extras/google/m2repository/io/vigour/plugin/core/
     Required by:
         android:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.507 secs
ERR! android Error: failed command
ERR! android     at ChildProcess.<anonymous> (/Users/ninjatux/workspace/vigour-native/lib/exe.js:41:21)
ERR! android     at emitTwo (events.js:87:13)
ERR! android     at ChildProcess.emit (events.js:172:7)
ERR! android     at maybeClose (internal/child_process.js:818:16)
ERR! android     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! android     at emitOne (events.js:77:13)
ERR! android     at Socket.emit (events.js:169:7)
ERR! android     at Pipe._onclose (net.js:469:12)
ERR! android  { [Error: failed command]
ERR! android   info:
ERR! android    { code: 1,
ERR! android      command: './gradlew assembleRelease -PverCode=27 -PverName=2.1.4 -PandroidAppId=org.test -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********' } } {"stack":"Error: failed command\n    at ChildProcess.<anonymous> (/Users/ninjatux/workspace/vigour-native/lib/exe.js:41:21)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:818:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:469:12)","message":"failed command","info":{"code":1,"command":"./gradlew assembleRelease -PverCode=27 -PverName=2.1.4 -PandroidAppId=org.test -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********"}} Error: failed command
ERR! android     at ChildProcess.<anonymous> (/Users/ninjatux/workspace/vigour-native/lib/exe.js:41:21)
ERR! android     at emitTwo (events.js:87:13)
ERR! android     at ChildProcess.emit (events.js:172:7)
ERR! android     at maybeClose (internal/child_process.js:818:16)
ERR! android     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! android     at emitOne (events.js:77:13)
ERR! android     at Socket.emit (events.js:169:7)
ERR! android     at Pipe._onclose (net.js:469:12)
ERR! oops Error: failed command
ERR! oops     at ChildProcess.<anonymous> (/Users/ninjatux/workspace/vigour-native/lib/exe.js:41:21)
ERR! oops     at emitTwo (events.js:87:13)
ERR! oops     at ChildProcess.emit (events.js:172:7)
ERR! oops     at maybeClose (internal/child_process.js:818:16)
ERR! oops     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! oops     at emitOne (events.js:77:13)
ERR! oops     at Socket.emit (events.js:169:7)
ERR! oops     at Pipe._onclose (net.js:469:12)
ERR! oops  { [Error: failed command]
ERR! oops   info:
ERR! oops    { code: 1,
ERR! oops      command: './gradlew assembleRelease -PverCode=27 -PverName=2.1.4 -PandroidAppId=org.test -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********' } } Error: failed command
ERR! oops     at ChildProcess.<anonymous> (/Users/ninjatux/workspace/vigour-native/lib/exe.js:41:21)
ERR! oops     at emitTwo (events.js:87:13)
ERR! oops     at ChildProcess.emit (events.js:172:7)
ERR! oops     at maybeClose (internal/child_process.js:818:16)
ERR! oops     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! oops     at emitOne (events.js:77:13)
ERR! oops     at Socket.emit (events.js:169:7)
ERR! oops     at Pipe._onclose (net.js:469:12)
    3) should succeed in under 60000 milliseconds!


  16 passing (24s)
  3 pending
  3 failing

  1) android-scripts installImages should create launch icons from image:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1

      at test/node/android/builder/index.js:186:44
      at node_modules/promise/lib/core.js:33:15
      at flush (node_modules/asap/asap.js:27:13)

  2) android-scripts installImages should create splash screens from image:

      AssertionError: expected 0 to deeply equal 1
      + expected - actual

      -0
      +1

      at test/node/android/builder/index.js:198:44
      at node_modules/promise/lib/core.js:33:15
      at flush (node_modules/asap/asap.js:27:13)

  3) android build should succeed in under 60000 milliseconds!:
     Error: failed command
      at ChildProcess.<anonymous> (lib/exe.js:41:21)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at Pipe._onclose (net.js:469:12)



info gaston test 3 'tests failed'

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/ninjatux/.nvm-fish/v4.2.2/bin/node" "/Users/ninjatux/.nvm-fish/v4.2.2/bin/npm" "run" "test-android"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! vigour-wrapper@1.0.2 test-android: `npm run buildtestapp && gaston test -r node -s test/node/android/`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the vigour-wrapper@1.0.2 test-android script 'npm run buildtestapp && gaston test -r node -s test/node/android/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vigour-wrapper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run buildtestapp && gaston test -r node -s test/node/android/
npm ERR! You can get their info via:
npm ERR!     npm owner ls vigour-wrapper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ninjatux/workspace/vigour-native/npm-debug.log
```

#### test-samsungtv
Looks like it works fine. The build creates a folder inside `test/app/build` with the samsungtv build

@shawninder are those results the same on your machine?
@michielibiza is the android build something that you can fix?

**Comment by shawninder** [comment]
@ninjatux Running **buildtestapp** or `npm run buildtestapp` should create or update **build.js**, **build.css** and **build.html** in `test/app`

**Comment by shawninder** [comment]
@ninjatux `npm run test-bridge` should be running `gaston test -r browser -s test/browser/bridge/`, not `gaston test -r browser -s test/phantom/bridge/`. I forgot to change it since gaston changed this. This will be fixed in my next push

**Comment by shawninder** [comment]
@ninjatux `npm run test-ios` indeed creates a project which, when run, produces a green screen. This is normal, because that's all the test app does. Notice the code in **test/app/src/index.js**:
```
'use strict'

require('./global.less')
```

**Comment by shawninder** [comment]
@ninjatux As for `npm run test-android`, two of the failing tests (the two `android-scripts installImages` tests) are known bugs due to the switch to vjs config. @michielibiza knows about this and intends to fix them soon. The other bug is more serious, but I don't get it anymore. It was fixed verty recently, so could you (Valerio) make sure everything is up to date and try again?

**Comment by michielibiza** [comment]
Indeed, the error you describe above for the android build seems to be a
gaston issue. I can't help you there...

Op ma 9 nov. 2015 18:06 schreef Shawn Inder <notifications@github.com>:

**Comment by shawninder** [comment]
@michielibiza Isn't this the infamous maven bug?

**Comment by michielibiza** [comment]
@shawninder @ninjatux 
Yes, that is a lot better :) Somehow the dependency is 'old' it's trying to find `io.vigour.plugin:core:+` but I've renamed that to `io.vigour:plugin-core:+` weeks ago. So it's a version problem. I'll look into the code now, maybe some merge went awry...

**Comment by michielibiza** [comment]
Ok I just pushed the fix (very weird that that error was still there...) should work now except the failing tests of the image stuff

**Comment by ninjatux** [comment]
@michielibiza the build works and as expected tests on images still fails
@shawninder why the bug was not showing up in your machine?Some config that you had and I don't?

**Comment by shawninder** [comment]
@ninjatux no idea

**Comment by vidbina** [comment]
Black magic

**Comment by shawninder** [comment]
Happens a lot these days
